### ISSUE TITLE
No process relationship is recorded

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#101]
Running the first test in the tests directory, it reports processes:

> p0 a b:process .
> p0 b:cmd "gcc -c f1.c" .
> p1      a       b:process .
> p1      b:cmd   "/usr/lib/gcc/x86_64-linux-gnu/11/cc1 -quiet -imultiarch x86_64-linux-gnu f1.c -quiet -dumpbase f1.c -dumpbase-ext .c -mtune=generic -march=x86-64 -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -fcf-protection -o /tmp/ccDu6HTo.s" .
> p2      a       b:process .
> p2      b:cmd   "as --64 -o f1.o /tmp/ccDu6HTo.s" .

but no relationship between them (i.e. p0 forked p1)

**Comment by fvalasiad** [comment]
@zvr Hmmmm yes indeed because we only capture processes that use `execve(2)` and `execveat(2)` to launch other programs(such as a compiler, linker etc).

In other words a forked process isn't actually detected until it calls one of the above `syscalls`. You are now suggesting that we should also record spawning process.

Point is i can see three ways in which processes are spawned:

`fork(2)`
`vfork(2)`
`clone(2)`

Would we be interested in differentiating each other and recording other stuff? Before i got involved in system programming all i knew was that parallel programming using threads was different from parallel programming using processes. I am aware that `fork(2)` and `vfork(2)` actually spawn another process so they probably fall into the latter category. What about `clone(2)` though?

**Comment by fvalasiad** [comment]
Well after some studying i think i get it now. `fork(2)` is the old way of doing things and `clone(2)` is something new introduced in linux that has more functionality(including the ability to create threads).

So would these suffice?
`p1 forked p2`
`p1 vforked p2`
`p1 cloned p2`

**Comment by zvr** [comment]
The exact way a process is created is an implementation detail, not relevant to us.
```
p1   b:creates   p2
````
is enough,

**Comment by fvalasiad** [comment]
@zvr How will we go about `process_start` though? So far we would start counting it since the `exec(2)` call. Doesn't it make sense to instead move it upon process creation?

**Comment by fvalasiad** [comment]
@zvr To be precise right now `record_process_start(3)` prints
[0] `p1 a         process`
[1] `p1 b:cmd  <cmd>`
[2] `p1 b:start <time>`

I think it makes sense to move **[0]** and **[2]** at process creation. Would it perhaps make sense to also rename **[1]** to be:
`p1 execs <cmd>`?

**Comment by zvr** [comment]
No, don't over-complicate it.
No need to really handle all the different steps of fork/exec, as they are not relevant to us.
