### ISSUE TITLE
First executable file not recorded 

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#126]
Although for each (sub-)process created the executable file is correctly recorded, this does not happen for the main process (the one given in the command line).

This can be easily verified, as the first file entry in every output should have been this executable.

**Comment by fvalasiad** [comment]
@zvr Hmmmmm plugging-in a solution brings another bug to the surface.

`absolutepath(3)` is buggy, because it doesn't take into consideration files found through `PATH`. It will treat said paths as "relative" and instead try to evaluate for example `/proc/<pid>/cwd/ls`.

Any handy tools to address that other than the standard "potentially naive" approach? Naive approach being:

Use `getenv(3)` to load `PATH` into a variable and start looping over it to  see if a file identified by a given `path` exists.
If not, try `/proc/<pid>/cwd/ls`.

Gotta take into consideration that this adds complexity to `absolutepath(3)`. Said feature isn't probably used for source files by the compiler anyways(i doubt any project's source files, other than perhaps libs which are accessed using an absolute path, are located in `PATH` and not somewhere locally). So perhaps we should give up on using `absolutepath(3)` in `execve` and start looking for alternatives such as reading the path from `cmdline`
